version: "3.8"
services:
  postgres:
    image: postgres:14.8
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/posgresql/data
    ports:
      - 5432:5432
volumes:
  postgres:
